/*data.js*/
const folders = {
  "Standard1": [
    "1.1.docx.pdf",
    "1.2.docx.pdf",
    "1.3.docx.pdf",
    "1.4.docx.pdf",
    "1.5.docx.pdf",
    "1.6.docx.pdf",
    "1.7.docx.pdf",
    "1.8.docx.pdf",
    "1.9.docx.pdf",
    "1.10.docx.pdf",
    "1.11.docx.pdf"
  ],
  "Standard2/Advanced Emergency Medical Technician": [
    "2.A.1.docx.pdf",
    "2.A.2.docx.pdf",
    "2.A.3.docx.pdf",
    "2.A.4.docx.pdf",
    "2.A.5.docx.pdf",
    "2.A.6.docx.pdf",
    "2.A.7.docx.pdf",
    "2.A.8.docx.pdf",
    "2.B.1.docx.pdf",
    "2.B.2.docx.pdf",
    "2.B.3.docx.pdf",
    "2.B.4.docx.pdf",
    "2.C.1.docx.pdf",
    "2.C.2.docx.pdf",
    "2.C.3.docx.pdf",
    "2.C.4.docx.pdf",
    "2.C.5.docx.pdf",
    "2.C.6.docx.pdf",
    "2.C.7.docx.pdf",
    "2.C.8.docx.pdf",
    "2.C.9.docx.pdf",
    "2.D.1.docx.pdf",
    "2.D.2.docx.pdf",
    "2.D.3.docx.pdf",
    "2.D.4.docx.pdf",
    "2.D.5.docx.pdf",
    "2.D.6.docx.pdf",
    "2.D.7.docx.pdf",
    "2.D.8.docx.pdf",
    "2.D.9.docx.pdf",
    "2.D.10.docx.pdf",
    "2.D.11.docx.pdf",
    "2.D.12.docx.pdf",
    "2.D.13.docx.pdf",
    "2.E.1.docx.pdf",
    "2.E.2.docx.pdf",
    "2.E.3.docx.pdf",
    "2.E.4.docx.pdf",
    "2.E.5.docx.pdf",
    "2.F.1.docx.pdf",
    "2.F.2.docx.pdf",
    "2.F.3.docx.pdf",
    "2.F.4.docx.pdf",
    "2.F.5.docx.pdf",
    "2.F.6.docx.pdf",
    "2.F.7.docx.pdf"
  ],
  "Standard2/Automation Technology": [
    "2.A.1.docx.pdf",
    "2.A.2.docx.pdf",
    "2.A.3.docx.pdf",
    "2.A.4.docx.pdf",
    "2.A.5.docx.pdf",
    "2.A.6.docx.pdf",
    "2.A.7.docx.pdf",
    "2.A.8.docx.pdf",
    "2.B.1.docx.pdf",
    "2.B.2.docx.pdf",
    "2.B.3.docx.pdf",
    "2.B.4.docx.pdf",
    "2.C.1.docx.pdf",
    "2.C.2.docx.pdf",
    "2.C.3.docx.pdf",
    "2.C.4.docx.pdf",
    "2.C.5.docx.pdf",
    "2.C.6.docx.pdf",
    "2.C.7.docx.pdf",
    "2.C.8.docx.pdf",
    "2.C.9.docx.pdf",
    "2.D.1.docx.pdf",
    "2.D.2.docx.pdf",
    "2.D.3.docx.pdf",
    "2.D.4.docx.pdf",
    "2.D.5.docx.pdf",
    "2.D.6.docx.pdf",
    "2.D.7.docx.pdf",
    "2.D.8.docx.pdf",
    "2.D.9.docx.pdf",
    "2.D.10.docx.pdf",
    "2.D.11.docx.pdf",
    "2.D.12.docx.pdf",
    "2.D.13.docx.pdf",
    "2.E.1.docx.pdf",
    "2.E.2.docx.pdf",
    "2.E.3.docx.pdf",
    "2.E.4.docx.pdf",
    "2.E.5.docx.pdf",
    "2.F.1.docx.pdf",
    "2.F.2.docx.pdf",
    "2.F.3.docx.pdf",
    "2.F.4.docx.pdf",
    "2.F.5.docx.pdf",
    "2.F.6.docx.pdf",
    "2.F.7.docx.pdf"
  ],
  "Standard2/Automotive Technology": [
    "2.A.1.docx.pdf",
    "2.A.2.docx.pdf",
    "2.A.3.docx.pdf",
    "2.A.4.docx.pdf",
    "2.A.5.docx.pdf",
    "2.A.6.docx.pdf",
    "2.A.7.docx.pdf",
    "2.A.8.docx.pdf",
    "2.B.1.docx.pdf",
    "2.B.2.docx.pdf",
    "2.B.3.docx.pdf",
    "2.B.4.docx.pdf",
    "2.C.1.docx.pdf",
    "2.C.2.docx.pdf",
    "2.C.3.docx.pdf",
    "2.C.4.docx.pdf",
    "2.C.5.docx.pdf",
    "2.C.6.docx.pdf",
    "2.C.7.docx.pdf",
    "2.C.8.docx.pdf",
    "2.C.9.docx.pdf",
    "2.D.1.docx.pdf",
    "2.D.2.docx.pdf",
    "2.D.3.docx.pdf",
    "2.D.4.docx.pdf",
    "2.D.5.docx.pdf",
    "2.D.6.docx.pdf",
    "2.D.7.docx.pdf",
    "2.D.8.docx.pdf",
    "2.D.9.docx.pdf",
    "2.D.10.docx.pdf",
    "2.D.11.docx.pdf",
    "2.D.12.docx.pdf",
    "2.D.13.docx.pdf",
    "2.E.1.docx.pdf",
    "2.E.2.docx.pdf",
    "2.E.3.docx.pdf",
    "2.E.4.docx.pdf",
    "2.E.5.docx.pdf",
    "2.F.1.docx.pdf",
    "2.F.2.docx.pdf",
    "2.F.3.docx.pdf",
    "2.F.4.docx.pdf",
    "2.F.5.docx.pdf",
    "2.F.6.docx.pdf",
    "2.F.7.docx.pdf"
  ],
  "Standard2/Commercial Driver's License Class A": [
    "2.A.1.docx.pdf",
    "2.A.2.docx.pdf",
    "2.A.3.docx.pdf",
    "2.A.4.docx.pdf",
    "2.A.5.docx.pdf",
    "2.A.6.docx.pdf",
    "2.A.7.docx.pdf",
    "2.A.8.docx.pdf",
    "2.B.1.docx.pdf",
    "2.B.2.docx.pdf",
    "2.B.3.docx.pdf",
    "2.B.4.docx.pdf",
    "2.C.1.docx.pdf",
    "2.C.2.docx.pdf",
    "2.C.3.docx.pdf",
    "2.C.4.docx.pdf",
    "2.C.5.docx.pdf",
    "2.C.6.docx.pdf",
    "2.C.7.docx.pdf",
    "2.C.8.docx.pdf",
    "2.C.9.docx.pdf",
    "2.D.1.docx.pdf",
    "2.D.2.docx.pdf",
    "2.D.3.docx.pdf",
    "2.D.4.docx.pdf",
    "2.D.5.docx.pdf",
    "2.D.6.docx.pdf",
    "2.D.7.docx.pdf",
    "2.D.8.docx.pdf",
    "2.D.9.docx.pdf",
    "2.D.10.docx.pdf",
    "2.D.11.docx.pdf",
    "2.D.12.docx.pdf",
    "2.D.13.docx.pdf",
    "2.E.1.docx.pdf",
    "2.E.2.docx.pdf",
    "2.E.3.docx.pdf",
    "2.E.4.docx.pdf",
    "2.E.5.docx.pdf",
    "2.F.1.docx.pdf",
    "2.F.2.docx.pdf",
    "2.F.3.docx.pdf",
    "2.F.4.docx.pdf",
    "2.F.5.docx.pdf",
    "2.F.6.docx.pdf",
    "2.F.7.docx.pdf"
  ]
};

const checklistItems = ["Item 1", "Item 2", "Item 3"];

let flatFileList = [];
let currentFileIndex = 0;
let currentItem = 0;

const viewerEl = document.getElementById("pdfViewer");
const folderListEl = document.getElementById("folderList");
const checklistContainer = document.getElementById("checklistContainer");

// Expose to global scope so modules can access them
window.folders = folders;
window.checklistItems = checklistItems;
window.flatFileList = flatFileList;
window.currentFileIndex = currentFileIndex;
window.currentItem = currentItem;

window.viewerEl = viewerEl;
window.folderListEl = folderListEl;
window.checklistContainer = checklistContainer;
