/*data.js*/
const folders = {
  
  "Conditions": [
    "0.A.1 Combined.docx.pdf",
    "0.A.2.docx.pdf",
    "0.A.3.docx.pdf",
    "0.A.4 (Not Applicable).docx.pdf",
    "0.A.5.docx.pdf",
    "0.A.6.docx.pdf",
    "0.A.7 (Not Applicable).docx.pdf",
    "0.A.8 (Not Applicable).docx.pdf",
    "0.A.9.docx.pdf",
    "0.A.10.docx.pdf",
    "0.A.11.docx.pdf",
    "0.A.12.docx.pdf",
    "0.A.13.docx.pdf",
    "0.A.14 (Not Applicable).docx.pdf",
    "0.A.15.docx.pdf",
    "0.A.16.docx.pdf",
    "0.A.17.docx.pdf",
    "0.A.18 Combined.docx.pdf",
    "0.A.19 Combined.docx.pdf",
    "0.A.20 Combined.docx.pdf",
    "0.A.21 (Not Applicable).docx.pdf",
    "0.A.22 (Not Applicable).docx.pdf",
    "0.A.23.docx.pdf",
    "0.A.24.docx.pdf",
    "0.A.25.docx.pdf",
    "0.B.1.docx.pdf",
    "0.B.2 (Not Applicable).docx.pdf",
    "0.B.3.docx.pdf",
    "0.B.4.docx.pdf",
    "0.B.5.docx.pdf",
    "0.B.6.docx.pdf",
    "0.B.7.docx.pdf",
    "0.B.8 (Not Applicable).docx.pdf",
    "0.C.1.docx.pdf",
    "0.C.2 (Not Applicable).docx.pdf",
    "0.C.3.docx.pdf",
    "0.C.4.docx.pdf",
    "0.C.5.docx.pdf",
    "0.C.6 Combined.docx.pdf",
    "0.C.7.docx.pdf",
    "0.D.1 (Not Applicable).docx.pdf",
    "0.D.2 (Not Applicable).docx.pdf",
    "0.E.1 (Not Applicable).docx.pdf",
    "0.E.2 (Not Applicable).docx.pdf",
    "0.F.1 (Not Applicable).docx.pdf",
    "0.F.2 (Not Applicable).docx.pdf",
    "0.F.3 (Not Applicable).docx.pdf",
    "0.G.1.docx.pdf",
    "0.G.2.docx.pdf",
    "0.G.3.docx.pdf",
    "0.G.4.docx.pdf",
    "0.H.1.docx.pdf"
  ],

  "Worksheets": [
    "0.A.1 Worksheet A.1.docx.pdf",
    "0.A.1 Worksheet A.2.docx.pdf",
    "0.A.1 Worksheet A.3.docx.pdf",
    "0.A.1 Worksheet A.4.docx.pdf",
    "0.A.1 Worksheet A.5.docx.pdf",
    "0.A.1 Worksheet A.6.docx.pdf",
    "0.A.1 Worksheet A.7.docx.pdf",
    "0.A.1 Worksheet A.8.docx.pdf",
    "0.A.1 Worksheet A.9.docx.pdf",
    "0.A.1 Worksheet A.10.docx.pdf",
    "0.A.1 Worksheet A.11.docx.pdf",
    "0.A.1 Worksheet A.12.docx.pdf",
    "0.A.1 Worksheet A.13.docx.pdf",
    "0.A.1 Worksheet A.14.docx.pdf",
    "0.A.1 Worksheet A.15.docx.pdf",
    "0.A.1 Worksheet A.16.docx.pdf",
    "0.A.1 Worksheet B.1.docx.pdf",
    "0.A.1 Worksheet B.2.docx.pdf",
    "0.A.1 Worksheet B.3.docx.pdf",
    "0.A.1 Worksheet B.4.docx.pdf",
    "0.A.1 Worksheet B.5.docx.pdf",
    "0.A.18 Worksheet A.[#].docx.pdf",
    "0.A.18 Worksheet B.1.docx.pdf",
    "0.A.18 Worksheet B.2.docx.pdf",
    "0.A.18 Worksheet B.3.docx.pdf",
    "0.A.18 Worksheet B.4.docx.pdf",
    "0.A.18 Worksheet B.5.A.docx.pdf",
    "0.A.18 Worksheet B.5.B.docx.pdf",
    "0.A.18 Worksheet B.5.C.docx.pdf",
    "0.A.18 Worksheet B.5.D.docx.pdf",
    "0.A.18 Worksheet B.5.E.docx.pdf",
    "0.A.18 Worksheet B.6.A.docx.pdf",
    "0.A.18 Worksheet B.6.B.docx.pdf",
    "0.A.18 Worksheet B.6.C.docx.pdf",
    "0.A.18 Worksheet B.6.D.docx.pdf",
    "0.A.18 Worksheet B.7.docx.pdf",
    "0.A.19 Worksheet 1.docx.pdf",
    "0.A.19 Worksheet 2.docx.pdf",
    "0.A.19 Worksheet 3.docx.pdf",
    "0.A.19 Worksheet 4.docx.pdf",
    "0.A.19 Worksheet 5.docx.pdf",
    "0.A.19 Worksheet 6.docx.pdf",
    "0.A.19 Worksheet 7.A.docx.pdf",
    "0.A.19 Worksheet 7.B.docx.pdf",
    "0.A.19 Worksheet 7.C.docx.pdf",
    "0.A.19 Worksheet 7.D.docx.pdf",
    "0.A.19 Worksheet 8.docx.pdf",
    "0.A.19 Worksheet 9.docx.pdf",
    "0.A.19 Worksheet 10.docx.pdf",
    "0.A.20 Worksheet 1.docx.pdf",
    "0.A.20 Worksheet 2.docx.pdf",
    "0.A.20 Worksheet 3.docx.pdf",
    "0.A.20 Worksheet 4.docx.pdf",
    "0.A.20 Worksheet 5.docx.pdf",
    "0.A.20 Worksheet 6.docx.pdf",
    "0.A.20 Worksheet 7.docx.pdf",
    "0.A.20 Worksheet 8.docx.pdf",
    "0.A.20 Worksheet 9.docx.pdf",
    "0.A.20 Worksheet 10.docx.pdf",
    "0.A.20 Worksheet 11.docx.pdf",
    "0.A.20 Worksheet 12.docx.pdf",
    "0.A.20 Worksheet 13 (Not Applicable).docx.pdf",
    "0.A.20 Worksheet 14.docx.pdf",
    "0.A.20 Worksheet 15.docx.pdf",
    "0.A.20 Worksheet 16.docx.pdf",
    "0.A.20 Worksheet 17.docx.pdf",
    "0.A.20 Worksheet 18.docx.pdf",
    "0.A.20 Worksheet 19.docx.pdf",
    "0.A.20 Worksheet 20.docx.pdf",
    "0.A.20 Worksheet 21.docx.pdf",
    "0.A.20 Worksheet 22.docx.pdf",
    "0.A.20 Worksheet 23.1.docx.pdf",
    "0.A.20 Worksheet 23.2.docx.pdf",
    "0.A.20 Worksheet 23.3.docx.pdf",
    "0.A.20 Worksheet 23.4.docx.pdf"
  ],

  "Standard1": [
    "1.1.docx.pdf",
    "1.2.docx.pdf",
    "1.3.docx.pdf",
    "1.4.docx.pdf",
    "1.5.docx.pdf",
    "1.6.docx.pdf",
    "1.7.docx.pdf",
    "1.8.docx.pdf",
    "1.9.docx.pdf",
    "1.10.docx.pdf",
    "1.11.docx.pdf"
  ],
  /*
  "Standard2/Advanced Emergency Medical Technician": [
  "2.A.1.docx.pdf",
  "2.A.2.docx.pdf",
  "2.A.3.docx.pdf"
  ],
  "Standard2/Automation Technology": [
  "2.A.1.docx.pdf",
  "2.A.2.docx.pdf",
  "2.A.3.docx.pdf"
  ],
  */
  "Standard4": [
    "4.1.docx.pdf",
    "4.2.docx.pdf",
    "4.3.docx.pdf",
    "4.4.docx.pdf",
    "4.5.docx.pdf",
    "4.6.docx.pdf",
    "4.7.docx.pdf",
    "4.8.docx.pdf"
  ],
  
  "Standard5": [
    "5.A.1.docx.pdf",
    "5.A.2.docx.pdf",
    "5.A.3.docx.pdf",
    "5.A.4.docx.pdf",
    "5.A.5.docx.pdf",
    "5.A.6.docx.pdf",
    "5.A.7.docx.pdf",
    "5.A.8.docx.pdf",
    "5.B.1.docx.pdf",
    "5.B.2.docx.pdf",
    "5.B.3.docx.pdf",
    "5.B.4.docx.pdf",
    "5.B.5.docx.pdf"
  ],

"Standard6": [ 
  "6.A.1.docx.pdf",
  "6.A.2.docx.pdf",
  "6.A.3.docx.pdf",
  "6.A.4.docx.pdf",
  "6.A.5.docx.pdf",
  "6.A.6.docx.pdf",
  "6.A.7.docx.pdf",
  "6.A.8.docx.pdf",
  "6.B.1.docx.pdf",
  "6.B.2.docx.pdf",
  "6.B.3.docx.pdf",
  "6.B.4.docx.pdf",
  "6.B.5.docx.pdf",
  "6.C.1.docx.pdf",
  "6.C.2.docx.pdf",
  "6.C.3.docx.pdf",
  "6.C.4.docx.pdf",
  "6.C.5.docx.pdf",
  "6.C.6.docx.pdf",
  "6.C.7.docx.pdf",
  "6.C.8.docx.pdf",
  "6.C.9.docx.pdf"
],

"Standard7": [
  "7.1.docx.pdf",
  "7.2.docx.pdf",
  "7.3.docx.pdf",
  "7.4.docx.pdf",
  "7.5.docx.pdf",
  "7.6.docx.pdf",
  "7.7.docx.pdf",
  "7.8 (Not Applicable).docx.pdf",
  "7.9 (Not Applicable).docx.pdf",
  "7.10.docx.pdf",
  "7.11.docx.pdf",
  "7.12 (Not Applicable).docx.pdf",
  "7.13 (Not Applicable).docx.pdf",
  "7.14.docx.pdf",
  "7.15.docx.pdf",
  "7.16 (Not Applicable).docx.pdf",
  "7.17 (Not Applicable).docx.pdf",
  "7.18 (Not Applicable).docx.pdf",
  "7.19.docx.pdf",
  "7.20.docx.pdf",
  "7.21.docx.pdf",
  "7.22.docx.pdf",
  "7.23.docx.pdf",
  "7.24 Item.docx.pdf",
  "7.24 Worksheet 1.A.docx.pdf"
  ],

"Standard8": [
  "8.A.1.docx.pdf",
  "8.A.2.docx.pdf",
  "8.A.3.docx.pdf",
  "8.A.4.docx.pdf",
  "8.B.1.docx.pdf",
  "8.B.2.docx.pdf",
  "8.B.3.docx.pdf",
  "8.B.4.docx.pdf",
  "8.B.5 (Not Applicable).docx.pdf",
  "8.B.6 (Not Applicable).docx.pdf",
  "8.B.7.docx.pdf",
  "8.B.8.docx.pdf",
  "8.B.9.docx.pdf",
  "8.B.10.docx.pdf",
  "8.C.1.docx.pdf",
  "8.C.2.docx.pdf",
  "8.D.1.docx.pdf",
  "8.D.2.docx.pdf",
  "8.D.3.docx.pdf",
  "8.E.1.docx.pdf",
  "8.E.2.docx.pdf"
  ],

  "Standard9": [
  "9.1.docx.pdf",
  "9.2 (Not Applicable).docx.pdf",
  "9.3.docx.pdf",
  "9.4.docx.pdf",
  "9.5.docx.pdf"
  ],
  /*
  "Standard10": [
  "10.A.1.docx.pdf",
  "10.A.2.docx.pdf",
  "10.A.3.docx.pdf",
  "10.A.4.docx.pdf",
  "10.A.5.docx.pdf",
  "10.A.6.docx.pdf",
  "10.A.7.docx.pdf",
  "10.A.8.docx.pdf",
  "10.A.9.docx.pdf",
  "10.A.10.docx.pdf",
  "10.A.11.A.docx.pdf",
  "10.A.11.B.docx.pdf",
  "10.A.11.C.docx.pdf",
  "10.A.11.D.docx.pdf",
  "10.A.12.docx.pdf",
  "10.A.13.docx.pdf",
  "10.A.14.docx.pdf",
  "10.A.15.docx.pdf",
  "10.B.1.docx.pdf",
  "10.B.2.docx.pdf",
  "10.B.3.docx.pdf",
  "10.B.4.Item.docx.pdf",
  "10.B.4.docx.pdf",
  "10.C.1.docx.pdf",
  "10.C.2.docx.pdf",
  "10.C.3.docx.pdf",
  "10.C.4.docx.pdf",
  "10.C.5.docx.pdf",
  "10.D.1.docx.pdf",
  "10.D.2.docx.pdf",
  "10.D.3.docx.pdf",
  "10.D.4.docx.pdf",
  "10.D.5.docx.pdf",
  "10.D.6.docx.pdf",
  "10.D.7.docx.pdf",
  "10.D.8.docx.pdf",
  "10.D.9.docx.pdf",
  "10.E.1.docx.pdf",
  "10.E.2.docx.pdf",
  "10.E.3.docx.pdf",
  "10.E.4.docx.pdf",
  "10.E.5.docx.pdf"
  ]
  */
  "ISC - Beaver": [
    "0.C.6 Worksheet Beaver.1.docx.pdf",
    "0.C.6 Worksheet Beaver.2.docx.pdf",
    "0.C.6 Worksheet Beaver.3.docx.pdf",
    "0.C.6 Worksheet Beaver.4.docx.pdf",
    "0.C.6 Worksheet Beaver.5.docx.pdf",
    "0.C.6 Worksheet Beaver.6.docx.pdf",
    "0.C.6 Worksheet Beaver.7.docx.pdf",
    "0.C.6 Worksheet Beaver.8.docx.pdf",
    "0.C.6 Worksheet Beaver.9.docx.pdf",
    "0.C.6 Worksheet Beaver.10.docx.pdf",
    "0.C.6 Worksheet Beaver.11.docx.pdf",
    "0.C.6 Worksheet Beaver.12.docx.pdf",
    "0.C.6 Worksheet Beaver.13.docx.pdf",
    "0.C.6 Worksheet Beaver.14.docx.pdf",
    "0.C.6 Worksheet Beaver.15.docx.pdf",
    "0.C.6 Worksheet Beaver.16.docx.pdf",
    "0.C.6 Worksheet Beaver.17.docx.pdf",
    "0.C.6 Worksheet Beaver.18 (Not Applicable).docx.pdf"
  ],
  "ISC - Kane": [
    "0.C.6 Worksheet Kane.1.docx.pdf",
    "0.C.6 Worksheet Kane.2.docx.pdf",
    "0.C.6 Worksheet Kane.3.docx.pdf",
    "0.C.6 Worksheet Kane.4.docx.pdf",
    "0.C.6 Worksheet Kane.5.docx.pdf",
    "0.C.6 Worksheet Kane.6.docx.pdf",
    "0.C.6 Worksheet Kane.7.docx.pdf",
    "0.C.6 Worksheet Kane.8.docx.pdf",
    "0.C.6 Worksheet Kane.9.docx.pdf",
    "0.C.6 Worksheet Kane.10.docx.pdf",
    "0.C.6 Worksheet Kane.11.docx.pdf",
    "0.C.6 Worksheet Kane.12.docx.pdf",
    "0.C.6 Worksheet Kane.13.docx.pdf",
    "0.C.6 Worksheet Kane.14.docx.pdf",
    "0.C.6 Worksheet Kane.15.docx.pdf",
    "0.C.6 Worksheet Kane.16.docx.pdf",
    "0.C.6 Worksheet Kane.17.docx.pdf",
    "0.C.6 Worksheet Kane.18 (Not Applicable).docx.pdf"
  ],
    "ISC - Richfield": [
    "0.C.6 Worksheet Richfield.1.docx.pdf",
    "0.C.6 Worksheet Richfield.2.docx.pdf",
    "0.C.6 Worksheet Richfield.3.docx.pdf",
    "0.C.6 Worksheet Richfield.4.docx.pdf",
    "0.C.6 Worksheet Richfield.5.docx.pdf",
    "0.C.6 Worksheet Richfield.6.docx.pdf",
    "0.C.6 Worksheet Richfield.7.docx.pdf",
    "0.C.6 Worksheet Richfield.8.docx.pdf",
    "0.C.6 Worksheet Richfield.9.docx.pdf",
    "0.C.6 Worksheet Richfield.10.docx.pdf",
    "0.C.6 Worksheet Richfield.11.docx.pdf",
    "0.C.6 Worksheet Richfield.12.docx.pdf",
    "0.C.6 Worksheet Richfield.13.docx.pdf",
    "0.C.6 Worksheet Richfield.14.docx.pdf",
    "0.C.6 Worksheet Richfield.15.docx.pdf",
    "0.C.6 Worksheet Richfield.16.docx.pdf",
    "0.C.6 Worksheet Richfield.17.docx.pdf",
    "0.C.6 Worksheet Richfield.18 (Not Applicable).docx.pdf"
  ]
};

const associatedDocs = {

  // Conditions
  "0.A.1 Combined.docx.pdf": [""],
  "0.A.2.docx.pdf": [""],
  "0.A.3.docx.pdf": [""],
  "0.A.4 (Not Applicable).docx.pdf": [""],
  "0.A.5.docx.pdf": [""],
  "0.A.6.docx.pdf": [""],
  "0.A.7 (Not Applicable).docx.pdf": [""],
  "0.A.8 (Not Applicable).docx.pdf": [""],
  "0.A.9.docx.pdf": [""],
  "0.A.10.docx.pdf": [""],
  "0.A.11.docx.pdf": [""],
  "0.A.12.docx.pdf": [""],
  "0.A.13.docx.pdf": [""],
  "0.A.14 (Not Applicable).docx.pdf": [""],
  "0.A.15.docx.pdf": [""],
  "0.A.16.docx.pdf": [""],
  "0.A.17.docx.pdf": [""],
  "0.A.18 Combined.docx.pdf": [""],
  "0.A.19 Combined.docx.pdf": [""],
  "0.A.20 Combined.docx.pdf": [""],
  "0.A.21 (Not Applicable).docx.pdf": [""],
  "0.A.22.docx.pdf": [""],
  "0.A.23.docx.pdf": [""],
  "0.A.24.docx.pdf": [""],
  "0.A.25.docx.pdf": [""],
  "0.B.1.docx.pdf": [""],
  "0.B.2 (Not Applicable).docx.pdf": [""],
  "0.B.3.docx.pdf": [""],
  "0.B.4.docx.pdf": [""],
  "0.B.5.docx.pdf": [""],
  "0.B.6.docx.pdf": [""],
  "0.B.7.docx.pdf": [""],
  "0.B.8 (Not Applicable).docx.pdf": [""],
  "0.C.1.docx.pdf": [""],
  "0.C.2 (Not Applicable).docx.pdf": [""],
  "0.C.3.docx.pdf": [""],
  "0.C.4.docx.pdf": [""],
  "0.C.5.docx.pdf": [""],
  "0.C.6 Combined.docx.pdf": [""],
  "0.C.7.docx.pdf": [""],
  "0.D.1 (Not Applicable).docx.pdf": [""],
  "0.D.2 (Not Applicable).docx.pdf": [""],
  "0.E.1 (Not Applicable).docx.pdf": [""],
  "0.E.2 (Not Applicable).docx.pdf": [""],
  "0.F.1 (Not Applicable).docx.pdf": [""],
  "0.F.2 (Not Applicable).docx.pdf": [""],
  "0.F.3 (Not Applicable).docx.pdf": [""],
  "0.G.1.docx.pdf": [""],
  "0.G.2.docx.pdf": [""],
  "0.G.3.docx.pdf": [""],
  "0.G.4.docx.pdf": [""],
  "0.H.1.docx.pdf": [""],

  //Worksheets
// Worksheets
  "Worksheets/0.A.1 Worksheet A.1.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.2.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.3.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.4.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.5.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.6.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.7.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.8.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.9.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.10.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.11.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.12.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.13.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.14.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.15.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet A.16.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet B.1.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet B.2.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet B.3.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet B.4.docx.pdf": [""],
  "Worksheets/0.A.1 Worksheet B.5.docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet A.[#].docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet B.1.docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet B.2.docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet B.3.docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet B.4.docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet B.5.A.docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet B.5.B.docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet B.5.C.docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet B.5.D.docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet B.5.E.docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet B.6.A.docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet B.6.B.docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet B.6.C.docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet B.6.D.docx.pdf": [""],
  "Worksheets/0.A.18 Worksheet B.7.docx.pdf": [""],
  "Worksheets/0.A.19 Worksheet 1.docx.pdf": [""],
  "Worksheets/0.A.19 Worksheet 2.docx.pdf": [""],
  "Worksheets/0.A.19 Worksheet 3.docx.pdf": [""],
  "Worksheets/0.A.19 Worksheet 4.docx.pdf": [""],
  "Worksheets/0.A.19 Worksheet 5.docx.pdf": [""],
  "Worksheets/0.A.19 Worksheet 6.docx.pdf": [""],
  "Worksheets/0.A.19 Worksheet 7.A.docx.pdf": [""],
  "Worksheets/0.A.19 Worksheet 7.B.docx.pdf": [""],
  "Worksheets/0.A.19 Worksheet 7.C.docx.pdf": [""],
  "Worksheets/0.A.19 Worksheet 7.D.docx.pdf": [""],
  "Worksheets/0.A.19 Worksheet 8.docx.pdf": [""],
  "Worksheets/0.A.19 Worksheet 9.docx.pdf": [""],
  "Worksheets/0.A.19 Worksheet 10.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 1.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 2.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 3.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 4.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 5.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 6.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 7.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 8.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 9.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 10.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 11.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 12.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 13 (Not Applicable).docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 14.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 15.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 16.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 17.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 18.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 19.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 20.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 21.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 22.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 23.1.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 23.2.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 23.3.docx.pdf": [""],
  "Worksheets/0.A.20 Worksheet 23.4.docx.pdf": [""],

  //Standard1
  "Standard1/1.1.docx.pdf": ["SupportFiles/Standard1/SelfStudy2025_21.pdf", "SupportFiles/Standard1/Standard1.pdf"],
  "Standard1/1.2.docx.pdf": ["SupportFiles/Standard1/SelfStudy2025_21.pdf", "SupportFiles/Standard1/Standard1.pdf"],
  "Standard1/1.3.docx.pdf": ["SupportFiles/Standard1/SelfStudy2025_21.pdf", "SupportFiles/Standard1/Standard1.pdf"],
  "Standard1/1.4.docx.pdf": ["SupportFiles/Standard1/SelfStudy2025_22.pdf", "SupportFiles/Standard1/Standard1.pdf"],
  "Standard1/1.5.docx.pdf": ["SupportFiles/Standard1/SelfStudy2025_22.pdf", "SupportFiles/Standard1/Standard1.pdf"],
  "Standard1/1.6.docx.pdf": ["SupportFiles/Standard1/SelfStudy2025_22.pdf", "SupportFiles/Standard1/Standard1.pdf"],
  "Standard1/1.7.docx.pdf": ["SupportFiles/Standard1/SelfStudy2025_22.pdf", "SupportFiles/Standard1/Standard1.pdf"],
  "Standard1/1.8.docx.pdf": ["SupportFiles/Standard1/SelfStudy2025_22.pdf", "SupportFiles/Standard1/SelfStudy2025_23.pdf", "SupportFiles/Standard1/Standard1.pdf"],
  "Standard1/1.9.docx.pdf": ["SupportFiles/Standard1/SelfStudy2025_23.pdf", "SupportFiles/Standard1/Standard1.pdf"],
  "Standard1/1.10.docx.pdf": ["SupportFiles/Standard1/SelfStudy2025_23.pdf", "SupportFiles/Standard1/Standard1.pdf"],
  "Standard1/1.11.docx.pdf": ["SupportFiles/Standard1/SelfStudy2025_23.pdf", "SupportFiles/Standard1/Standard1.pdf"],

  //Standard4
  "Standard4/4.1.docx.pdf": ["SupportFiles/Standard4/SelfStudy2025_273.pdf"],
  "Standard4/4.2.docx.pdf": ["SupportFiles/Standard4/SelfStudy2025_273.pdf", "SupportFiles/Standard4/SelfStudy2025_274.pdf"],
  "Standard4/4.3.docx.pdf": ["SupportFiles/Standard4/SelfStudy2025_274.pdf"],
  "Standard4/4.4.docx.pdf": ["SupportFiles/Standard4/SelfStudy2025_274.pdf"],
  "Standard4/4.5.docx.pdf": ["SupportFiles/Standard4/SelfStudy2025_274.pdf"],
  "Standard4/4.6.docx.pdf": ["SupportFiles/Standard4/SelfStudy2025_274.pdf"],
  "Standard4/4.7.docx.pdf": ["SupportFiles/Standard4/SelfStudy2025_274.pdf", "SupportFiles/Standard4/SelfStudy2025_275.pdf"],
  "Standard4/4.8.docx.pdf": ["SupportFiles/Standard4/SelfStudy2025_275.pdf"],

  //Standard5
  "Standard5/5.A.1.docx.pdf": ["SupportFiles/Standard5/SelfStudy2025_Part276.pdf", "SupportFiles/Standard5/Standard5.pdf"],
  "Standard5/5.A.2.docx.pdf": ["SupportFiles/Standard5/SelfStudy2025_Part276.pdf", "SupportFiles/Standard5/Standard5.pdf"],
  "Standard5/5.A.3.docx.pdf": ["SupportFiles/Standard5/SelfStudy2025_Part276_277.pdf", "SupportFiles/Standard5/Standard5.pdf"],
  "Standard5/5.A.4.docx.pdf": ["SupportFiles/Standard5/SelfStudy2025_Part277.pdf", "SupportFiles/Standard5/Standard5.pdf"],
  "Standard5/5.A.5.docx.pdf": ["SupportFiles/Standard5/SelfStudy2025_Part277.pdf", "SupportFiles/Standard5/Standard5.pdf"],
  "Standard5/5.A.6.docx.pdf": ["SupportFiles/Standard5/SelfStudy2025_Part277.pdf", "SupportFiles/Standard5/Standard5.pdf"],
  "Standard5/5.A.7.docx.pdf": ["SupportFiles/Standard5/SelfStudy2025_Part277_278.pdf", "SupportFiles/Standard5/Standard5.pdf"],
  "Standard5/5.A.8.docx.pdf": ["SupportFiles/Standard5/SelfStudy2025_Part278.pdf", "SupportFiles/Standard5/Standard5.pdf"],
  "Standard5/5.B.1.docx.pdf": ["SupportFiles/Standard5/SelfStudy2025_Part278.pdf", "SupportFiles/Standard5/Standard5.pdf"],
  "Standard5/5.B.2.docx.pdf": ["SupportFiles/Standard5/SelfStudy2025_Part278.pdf", "SupportFiles/Standard5/Standard5.pdf"],
  "Standard5/5.B.3.docx.pdf": ["SupportFiles/Standard5/SelfStudy2025_Part278_279.pdf", "SupportFiles/Standard5/Standard5.pdf"],
  "Standard5/5.B.4.docx.pdf": ["SupportFiles/Standard5/SelfStudy2025_Part279.pdf", "SupportFiles/Standard5/Standard5.pdf"],
  "Standard5/5.B.5.docx.pdf": ["SupportFiles/Standard5/SelfStudy2025_Part279.pdf", "SupportFiles/Standard5/Standard5.pdf"],

  // Standard6
  "Standard6/6.A.1.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part281.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.A.2.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part281.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.A.3.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part281.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.A.4.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part281.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.A.5.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part281.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.A.6.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part282.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.A.7.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part282.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.A.8.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part282.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.B.1.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part282.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.B.2.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part283.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.B.3.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part283.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.B.4.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part283.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.B.5.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part283.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.C.1.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part283.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.C.2.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part283.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.C.3.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part283.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.C.4.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part283.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.C.5.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part284.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.C.6.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part284.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.C.7.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part284.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.C.8.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part284.pdf", "SupportFiles/Standard6/Standard6.pdf"],
  "Standard6/6.C.9.docx.pdf": ["SupportFiles/Standard6/SelfStudy2025_Part284_285.pdf", "SupportFiles/Standard6/Standard6.pdf"],

  //Standard7
  "Standard7/7.1.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part287.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.2.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part287.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.3.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part287_288.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.4.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part288.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.5.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part288.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.6.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part288.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.7.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part288_289.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.8 (Not Applicable).docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part289.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.9 (Not Applicable).docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part289.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.10.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part289_290.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.11.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part290.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.12 (Not Applicable).docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part290.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.13 (Not Applicable).docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part290.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.14.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part290.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.15.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part290_291.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.16 (Not Applicable).docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part291.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.17 (Not Applicable).docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part291.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.18 (Not Applicable).docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part291.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.19.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part291.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.20.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part292.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.21.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part292.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.22.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part292.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.23.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part292.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.24 Item.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part292.pdf", "SupportFiles/Standard7/Standard7.pdf"],
  "Standard7/7.24 Worksheet 1.A.docx.pdf": ["SupportFiles/Standard7/SelfStudy2025_Part292.pdf", "SupportFiles/Standard7/Standard7.pdf"],

  // Standard8
  "Standard8/8.A.1.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part295.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.A.2.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part295.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.A.3.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part295_296.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.A.4.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part296.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.B.1.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part296.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.B.2.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part296.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.B.3.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part296.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.B.4.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part297.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.B.5 (Not Applicable).docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part297.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.B.6 (Not Applicable).docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part297.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.B.7.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part297.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.B.8.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part297.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.B.9.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part297_298.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.B.10.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part298.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.C.1.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part298.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.C.2.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part298.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.D.1.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part299.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.D.2.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part299.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.D.3.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part299.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.E.1.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part299.pdf", "SupportFiles/Standard8/Standard8.pdf"],
  "Standard8/8.E.2.docx.pdf": ["SupportFiles/Standard8/SelfStudy2025_Part299_230.pdf", "SupportFiles/Standard8/Standard8.pdf"],

  //Standard9
  "Standard9/9.1.docx.pdf": ["SupportFiles/Standard9/SelfStudy2025_310.pdf"],
  "Standard9/9.2 (Not Applicable).docx.pdf": ["SupportFiles/Standard9/SelfStudy2025_310.pdf"],
  "Standard9/9.3.docx.pdf": ["SupportFiles/Standard9/SelfStudy2025_310.pdf", "SupportFiles/Standard9/SelfStudy2025_311.pdf"],
  "Standard9/9.4.docx.pdf": ["SupportFiles/Standard9/SelfStudy2025_311.pdf"],
  "Standard9/9.5.docx.pdf": ["SupportFiles/Standard9/SelfStudy2025_311.pdf"],

  /*
  //Standard10
  "Standard10/10.A.1.docx.pdf": "",
  "Standard10/10.A.2.docx.pdf": "",
  "Standard10/10.A.3.docx.pdf": "",
  "Standard10/10.A.4.docx.pdf": "",
  "Standard10/10.A.5.docx.pdf": "",
  "Standard10/10.A.6.docx.pdf": "",
  "Standard10/10.A.7.docx.pdf": "",
  "Standard10/10.A.8.docx.pdf": "",
  "Standard10/10.A.9.docx.pdf": "",
  "Standard10/10.A.10.docx.pdf": "",
  "Standard10/10.A.11.A.docx.pdf": "",
  "Standard10/10.A.11.B.docx.pdf": "",
  "Standard10/10.A.11.C.docx.pdf": "",
  "Standard10/10.A.11.D.docx.pdf": "",
  "Standard10/10.A.12.docx.pdf": "",
  "Standard10/10.A.13.docx.pdf": "",
  "Standard10/10.A.14.docx.pdf": "",
  "Standard10/10.A.15.docx.pdf": "",
  "Standard10/10.B.1.docx.pdf": "",
  "Standard10/10.B.2.docx.pdf": "",
  "Standard10/10.B.3.docx.pdf": "",
  "Standard10/10.B.4.Item.docx.pdf": "",
  "Standard10/10.B.4.docx.pdf": "",
  "Standard10/10.C.1.docx.pdf": "",
  "Standard10/10.C.2.docx.pdf": "",
  "Standard10/10.C.3.docx.pdf": "",
  "Standard10/10.C.4.docx.pdf": "",
  "Standard10/10.C.5.docx.pdf": "",
  "Standard10/10.D.1.docx.pdf": "",
  "Standard10/10.D.2.docx.pdf": "",
  "Standard10/10.D.3.docx.pdf": "",
  "Standard10/10.D.4.docx.pdf": "",
  "Standard10/10.D.5.docx.pdf": "",
  "Standard10/10.D.6.docx.pdf": "",
  "Standard10/10.D.7.docx.pdf": "",
  "Standard10/10.D.8.docx.pdf": "",
  "Standard10/10.D.9.docx.pdf": "",
  "Standard10/10.E.1.docx.pdf": "",
  "Standard10/10.E.2.docx.pdf": "",
  "Standard10/10.E.3.docx.pdf": "",
  "Standard10/10.E.4.docx.pdf": "",
  "Standard10/10.E.5.docx.pdf": ""
  */

  // ISC — Beaver
  "0.C.6 Worksheet Beaver.1.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.2.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.3.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.4.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.5.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.6.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.7.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.8.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.9.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.10.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.11.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.12.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.13.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.14.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.15.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.16.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.17.docx.pdf": [""],
  "0.C.6 Worksheet Beaver.18 (Not Applicable).docx.pdf": [""],
 
  // ISC — Kane
  "0.C.6 Worksheet Kane.1.docx.pdf": [""],
  "0.C.6 Worksheet Kane.2.docx.pdf": [""],
  "0.C.6 Worksheet Kane.3.docx.pdf": [""],
  "0.C.6 Worksheet Kane.4.docx.pdf": [""],
  "0.C.6 Worksheet Kane.5.docx.pdf": [""],
  "0.C.6 Worksheet Kane.6.docx.pdf": [""],
  "0.C.6 Worksheet Kane.7.docx.pdf": [""],
  "0.C.6 Worksheet Kane.8.docx.pdf": [""],
  "0.C.6 Worksheet Kane.9.docx.pdf": [""],
  "0.C.6 Worksheet Kane.10.docx.pdf": [""],
  "0.C.6 Worksheet Kane.11.docx.pdf": [""],
  "0.C.6 Worksheet Kane.12.docx.pdf": [""],
  "0.C.6 Worksheet Kane.13.docx.pdf": [""],
  "0.C.6 Worksheet Kane.14.docx.pdf": [""],
  "0.C.6 Worksheet Kane.15.docx.pdf": [""],
  "0.C.6 Worksheet Kane.16.docx.pdf": [""],
  "0.C.6 Worksheet Kane.17.docx.pdf": [""],
  "0.C.6 Worksheet Kane.18 (Not Applicable).docx.pdf": [""],

  // ISC — Richfield"
  "0.C.6 Worksheet Richfield.1.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.2.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.3.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.4.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.5.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.6.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.7.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.8.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.9.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.10.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.11.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.12.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.13.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.14.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.15.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.16.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.17.docx.pdf": [""],
  "0.C.6 Worksheet Richfield.18 (Not Applicable).docx.pdf": [""]

};

const associatedDocNames = {
  // Standard 1 Associated File Names
  "Standard1/1.1.docx.pdf": ["1.1 — Self Study", "Standard 1 — Self Study"],
  "Standard1/1.2.docx.pdf": ["1.2 — Self Study", "Standard 1 — Self Study"],
  "Standard1/1.3.docx.pdf": ["1.3 — Self Study", "Standard 1 — Self Study"],
  "Standard1/1.4.docx.pdf": ["1.4 — Self Study", "Standard 1 — Self Study"],
  "Standard1/1.5.docx.pdf": ["1.5 — Self Study", "Standard 1 — Self Study"],
  "Standard1/1.6.docx.pdf": ["1.6 — Self Study", "Standard 1 — Self Study"],
  "Standard1/1.7.docx.pdf": ["1.7 — Self Study", "Standard 1 — Self Study"],
  "Standard1/1.8.docx.pdf": ["1.8 — Self Study p.1", "1.8 — Self Study p.2", "Standard 1 — Self Study"],
  "Standard1/1.9.docx.pdf": ["1.9 — Self Study", "Standard 1 — Self Study"],
  "Standard1/1.10.docx.pdf": ["1.10 — Self Study", "Standard 1 — Self Study"],
  "Standard1/1.11.docx.pdf": ["1.11 — Self Study", "Standard 1 — Self Study"],

  // Standard 5 Associated File Names
  "Standard5/5.A.1.docx.pdf": ["5.A.1 — Self Study", "Standard 5 — Self Study"],
  "Standard5/5.A.2.docx.pdf": ["5.A.2 — Self Study", "Standard 5 — Self Study"],
  "Standard5/5.A.3.docx.pdf": ["5.A.3 — Self Study", "Standard 5 — Self Study"],
  "Standard5/5.A.4.docx.pdf": ["5.A.4 — Self Study", "Standard 5 — Self Study"],
  "Standard5/5.A.5.docx.pdf": ["5.A.5 — Self Study", "Standard 5 — Self Study"],
  "Standard5/5.A.6.docx.pdf": ["5.A.6 — Self Study", "Standard 5 — Self Study"],
  "Standard5/5.A.7.docx.pdf": ["5.A.7 — Self Study", "Standard 5 — Self Study"],
  "Standard5/5.A.8.docx.pdf": ["5.A.8 — Self Study", "Standard 5 — Self Study"],
  "Standard5/5.B.1.docx.pdf": ["5.B.1 — Self Study", "Standard 5 — Self Study"],
  "Standard5/5.B.2.docx.pdf": ["5.B.2 — Self Study", "Standard 5 — Self Study"],
  "Standard5/5.B.3.docx.pdf": ["5.B.3 — Self Study", "Standard 5 — Self Study"],
  "Standard5/5.B.4.docx.pdf": ["5.B.4 — Self Study", "Standard 5 — Self Study"],
  "Standard5/5.B.5.docx.pdf": ["5.B.5 — Self Study", "Standard 5 — Self Study"],

  // Standard 6 Associated File Names
  "Standard6/6.A.1.docx.pdf": ["6.A.1 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.A.2.docx.pdf": ["6.A.2 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.A.3.docx.pdf": ["6.A.3 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.A.4.docx.pdf": ["6.A.4 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.A.5.docx.pdf": ["6.A.5 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.A.6.docx.pdf": ["6.A.6 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.A.7.docx.pdf": ["6.A.7 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.A.8.docx.pdf": ["6.A.8 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.B.1.docx.pdf": ["6.B.1 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.B.2.docx.pdf": ["6.B.2 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.B.3.docx.pdf": ["6.B.3 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.B.4.docx.pdf": ["6.B.4 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.B.5.docx.pdf": ["6.B.5 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.C.1.docx.pdf": ["6.C.1 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.C.2.docx.pdf": ["6.C.2 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.C.3.docx.pdf": ["6.C.3 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.C.4.docx.pdf": ["6.C.4 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.C.5.docx.pdf": ["6.C.5 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.C.6.docx.pdf": ["6.C.6 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.C.7.docx.pdf": ["6.C.7 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.C.8.docx.pdf": ["6.C.8 — Self Study", "Standard 6 — Self Study"],
  "Standard6/6.C.9.docx.pdf": ["6.C.9 — Self Study", "Standard 6 — Self Study"],

  // Standard 7 Associated File Names
  "Standard7/7.1.docx.pdf": ["7.1 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.2.docx.pdf": ["7.2 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.3.docx.pdf": ["7.3 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.4.docx.pdf": ["7.4 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.5.docx.pdf": ["7.5 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.6.docx.pdf": ["7.6 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.7.docx.pdf": ["7.7 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.8 (Not Applicable).docx.pdf": ["7.8 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.9 (Not Applicable).docx.pdf": ["7.9 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.10.docx.pdf": ["7.10 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.11.docx.pdf": ["7.11 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.12 (Not Applicable).docx.pdf": ["7.12 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.13 (Not Applicable).docx.pdf": ["7.13 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.14.docx.pdf": ["7.14 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.15.docx.pdf": ["7.15 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.16 (Not Applicable).docx.pdf": ["7.16 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.17 (Not Applicable).docx.pdf": ["7.17 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.18 (Not Applicable).docx.pdf": ["7.18 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.19.docx.pdf": ["7.19 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.20.docx.pdf": ["7.20 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.21.docx.pdf": ["7.21 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.22.docx.pdf": ["7.22 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.23.docx.pdf": ["7.23 — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.24 Item.docx.pdf": ["7.24.Item — Self Study", "Standard 7 — Self Study"],
  "Standard7/7.24 Worksheet 1.A.docx.pdf": ["7.2.Worksheet.1.A — Self Study", "Standard 7 — Self Study"],

  // Standard 8 Associated File Names
  "Standard8/8.A.1.docx.pdf": ["8.A.1 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.A.2.docx.pdf": ["8.A.2 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.A.3.docx.pdf": ["8.A.3 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.A.4.docx.pdf": ["8.A.4 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.B.1.docx.pdf": ["8.B.1 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.B.2.docx.pdf": ["8.B.2 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.B.3.docx.pdf": ["8.B.3 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.B.4.docx.pdf": ["8.B.4 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.B.5 (Not Applicable).docx.pdf": ["8.B.5 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.B.6 (Not Applicable).docx.pdf": ["8.B.6 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.B.7.docx.pdf": ["8.B.7 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.B.8.docx.pdf": ["8.B.8 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.B.9.docx.pdf": ["8.B.9 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.B.10.docx.pdf": ["8.B.10 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.C.1.docx.pdf": ["8.C.1 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.C.2.docx.pdf": ["8.C.2 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.D.1.docx.pdf": ["8.D.1 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.D.2.docx.pdf": ["8.D.2 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.D.3.docx.pdf": ["8.D.3 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.E.1.docx.pdf": ["8.E.1 — Self Study", "Standard 8 — Self Study"],
  "Standard8/8.E.2.docx.pdf": ["8.E.2 — Self Study", "Standard 8 — Self Study"]

  // default will be used if not listed here
};

window.associatedDocs = associatedDocs;
window.associatedDocNames = associatedDocNames;

const checklistItems = [
  "Item 1",
  "Item 2",
  "2.A.1",
  "2.A.2"
];

let flatFileList = [];
let currentFileIndex = 0;
let currentItem = 0;

const viewerEl = document.getElementById("pdfViewer");
const folderListEl = document.getElementById("folderList");
const checklistContainer = document.getElementById("checklistContainer");

// Expose to global scope so modules can access them
window.folders = folders;
window.checklistItems = checklistItems;
window.flatFileList = flatFileList;
window.currentFileIndex = currentFileIndex;
window.currentItem = currentItem;

window.viewerEl = viewerEl;
window.folderListEl = folderListEl;
window.checklistContainer = checklistContainer;
